# package 
PACKAGE=
# current directory relative to top directory
SRCDIR=semantic
# subdirectories
SUBDIRS=base-name class entity enum func message name nav ns obj output param scope tdef tmpl type using util vdf lzz
# include files
INCFILES=
# library lzz files
LIBLZZFILES=
# library source files
LIBCPPFILES=
# program lzz files
PRGLZZFILES=
# program source files
PRGCPPFILES=
# programs
PROGRAMS=
# common makefile
include $(PRJDIR)/maketools/Make.common
