# package 
PACKAGE=smtc
# current directory relative to top directory
SRCDIR=semantic/scope
# subdirectories
SUBDIRS=
# include files
INCFILES=
# library lzz files
LIBLZZFILES=
# library source files
LIBCPPFILES=
# program lzz files
PRGLZZFILES=
# program source files
PRGCPPFILES=
# programs
PROGRAMS=
# common makefile
include $(PRJDIR)/maketools/Make.common
