# package 
PACKAGE=
# current directory relative to top directory
SRCDIR=gram
# subdirectories
SUBDIRS=lexer message parser prep rules util
# include files
INCFILES=
# library lzz files
LIBLZZFILES=
# library source files
LIBCPPFILES=
# program lzz files
PRGLZZFILES=
# program source files
PRGCPPFILES=
# programs
PROGRAMS=
# common makefile
include $(PRJDIR)/maketools/Make.common
